In [138]:
import pandas as pd
import pickle
from sklearn import preprocessing

# Load the AI model
model = pickle.load(open('model.pkl', 'rb'))

data=pd.read_csv("data.csv")
test=pd.read_csv("test.csv")

data = pd.concat([data, test])

pd.set_option("display.max_columns", None)
pd.set_option("display.width",500)


for col in data.columns:
      if data[col].dtypes == "bool":
        data[col]= data[col].astype(int)
        
def label_encoder(dataframe):
    for col in dataframe.columns:
        if dataframe[col].nunique() < 3 and str(dataframe[col].dtypes) in ["category","object"] :
            le= preprocessing.LabelEncoder()
            dataframe[col] = le.fit_transform(dataframe[col].astype(str))
            return dataframe
        
data = label_encoder(data)

def one_hot(dataframe):
    for col in dataframe.columns:
        if 2 < dataframe[col].nunique() < 8 and str(dataframe[col].dtypes) in ["category","object"]:
            dataframe=pd.get_dummies(dataframe,columns=[col])
    return dataframe

data = one_hot(data)

data["person_emp_length"]= data["person_emp_length"].fillna(data["person_emp_length"].mean())
data["loan_int_rate"]= data["loan_int_rate"].fillna(data["loan_int_rate"].mean())

y = data.iloc[-1]
y.drop('loan_status')
y = model.predict([22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3])

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,person_home_ownership_MORTGAGE,person_home_ownership_OTHER,person_home_ownership_OWN,person_home_ownership_RENT,loan_intent_DEBTCONSOLIDATION,loan_intent_EDUCATION,loan_intent_HOMEIMPROVEMENT,loan_intent_MEDICAL,loan_intent_PERSONAL,loan_intent_VENTURE,loan_grade_A,loan_grade_B,loan_grade_C,loan_grade_D,loan_grade_E,loan_grade_F
0,22,59000,123.0,35000,16.020000,1,0.59,1,3,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0
1,21,9600,5.0,1000,11.140000,0,0.10,0,2,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0
2,25,9600,1.0,5500,12.870000,1,0.57,0,3,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0
3,23,65500,4.0,35000,15.230000,1,0.53,0,2,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0
4,24,54400,8.0,35000,14.270000,1,0.55,1,4,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
205,33,53000,13.0,10000,15.960000,0,0.19,0,9,0,0,0,1,0,1,0,0,0,0,0,0,1,0,0,0
206,29,72072,4.0,12000,8.490000,0,0.17,0,8,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0
207,28,72087,10.0,16000,12.247407,0,0.22,0,6,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0
208,27,53000,7.0,10000,10.250000,0,0.19,0,5,0,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0
0,22,59000,123.0,35000,16.020000,1,0.59,1,3,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0

person_age                           22.00
person_income                     59000.00
person_emp_length                   123.00
loan_amnt                         35000.00
loan_int_rate                        16.02
loan_percent_income                   0.59
cb_person_default_on_file             1.00
cb_person_cred_hist_length            3.00
person_home_ownership_MORTGAGE        0.00
person_home_ownership_OTHER           0.00
person_home_ownership_OWN             0.00
person_home_ownership_RENT            1.00
loan_intent_DEBTCONSOLIDATION         0.00
loan_intent_EDUCATION                 0.00
loan_intent_HOMEIMPROVEMENT           0.00
loan_intent_MEDICAL                   0.00
loan_intent_PERSONAL                  1.00
loan_intent_VENTURE                   0.00
loan_grade_A                          0.00
loan_grade_B                          0.00
loan_grade_C                          0.00
loan_grade_D                          1.00
loan_grade_E                          0.00
loan_grade_F                          0.00
Name: 0, dtype: float64

In [136]:
y

1

In [142]:
!pip install pickle

ERROR: Could not find a version that satisfies the requirement pickle (from versions: none)
ERROR: No matching distribution found for pickle